DROP TABLE IF EXISTS Usuarios;
DROP TABLE IF EXISTS Alunos;
DROP TABLE IF EXISTS Cargo;

CREATE TABLE Cargo (
  Nome_Cargo TEXT UNIQUE NOT NULL,
  CargoID INTEGER NOT NULL PRIMARY KEY UNIQUE 
);

CREATE TABLE Usuarios (
  Id_Usuario INTEGER PRIMARY KEY AUTOINCREMENT,
  Nome TEXT UNIQUE NOT NULL,
  Cargo TEXT,
  CargoId INTEGER,
  CPF TEXT UNIQUE,
  Is_admin INTEGER,
  User_login TEXT UNIQUE NOT NULL,
  Senha TEXT NOT NULL,
  FOREIGN KEY (CargoID) REFERENCES Cargo(CargoID)
);

CREATE TABLE Alunos (
  Id_Aluno INTEGER PRIMARY KEY AUTOINCREMENT,
  Nome_Completo TEXT NOT NULL,
  RA TEXT UNIQUE,
  Criado_Por TEXT,
  Data_Nascimento TEXT,
  RM INTEGER UNIQUE NOT NULL,
  Data_Alteracao NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (Criado_Por) REFERENCES Usuarios(Id_Usuario)
);
